"""
Phase 9C: Email Service for Security Alerts
===========================================
Formats and transmits professional, confidential security alert notifications.
- Strict tenant recipient delivery: sent exclusively to CloudAccount owner.
- Sanitized content: zero exposure of AWS credentials, IAM trust secrets, tokens, or passwords.
- Controlled by CSPM_EMAIL_ENABLED (default: False).
- Error-safe: SMTP failures never raise to calling scanner/monitoring processes.
"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Tuple, Optional
from datetime import datetime

from app.core.config import settings
from app.models.monitoring import SecurityAlert
from app.models.cloud import CloudAccount

logger = logging.getLogger("cspm.notifications.email")


class EmailService:
    """
    Handles formatting and outbound transmission of CSPM security notification emails.
    """

    @classmethod
    def is_enabled(cls) -> bool:
        """Returns True iff system-wide email notifications are enabled."""
        return bool(getattr(settings, "CSPM_EMAIL_ENABLED", False))

    @classmethod
    def format_subject(cls, alert: SecurityAlert) -> str:
        """Generates standard, professional subject line."""
        if alert.alert_type == "SCAN_FAILED":
            return "[CSPM] Cloud Scan Failed"
        elif alert.alert_type == "RISK_INCREASED":
            return f"[CSPM] {alert.severity.upper()} Risk Increase Detected"
        else:
            return f"[CSPM] {alert.severity.upper()} Security Finding Detected"

    @classmethod
    def build_email_bodies(
        cls,
        alert: SecurityAlert,
        cloud_account: CloudAccount,
    ) -> Tuple[str, str]:
        """
        Builds both plain-text and HTML versions of the security alert email.
        Guaranteed to contain zero AWS keys, session tokens, external IDs, or secrets.
        """
        account_name = cloud_account.name or "Cloud Account"
        account_id = cloud_account.account_identifier or "N/A"
        alert_title = alert.title
        severity = alert.severity.upper()
        status = alert.status
        detected_time = alert.first_detected_at.strftime("%Y-%m-%d %H:%M:%S UTC") if alert.first_detected_at else "N/A"
        description = alert.description or "No description provided."

        # Risk score calculation
        risk_score = "N/A"
        if alert.finding and alert.finding.risk_score is not None:
            risk_score = f"{alert.finding.risk_score:.1f} / 100"
        elif alert.current_value:
            try:
                val = float(alert.current_value)
                risk_score = f"{val:.1f} / 100"
            except ValueError:
                risk_score = alert.current_value

        # Remediation recommendation
        remediation = "Inspect affected resources in the CSPM console and apply least-privilege configuration."
        if alert.finding and alert.finding.rule and alert.finding.rule.remediation:
            remediation = alert.finding.rule.remediation

        frontend_url = getattr(settings, "CSPM_FRONTEND_URL", "http://localhost:5173").rstrip("/")
        alert_url = f"{frontend_url}/alerts"

        # Plain Text Body
        text_body = f"""Cloud Security Posture Management
Security Alert

AWS Account:
{account_name}

Account ID:
{account_id}

Alert:
{alert_title}

Severity:
{severity}

Risk Score:
{risk_score}

Status:
{status}

Detected:
{detected_time}

Description:
{description}

Recommended Action:
{remediation}

View Alert:
{alert_url}

This notification was generated by your CSPM monitoring system.
"""

        # HTML Body
        severity_color = "#DC2626" if severity == "CRITICAL" else "#EA580C" if severity == "HIGH" else "#D97706"

        html_body = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{cls.format_subject(alert)}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0B0F19; color: #F3F4F6; margin: 0; padding: 24px;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #111827; border: 1px solid #1F2937; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.5);">
    <div style="background-color: #1F2937; padding: 18px 24px; border-bottom: 1px solid #374151;">
      <h2 style="margin: 0; font-size: 16px; color: #60A5FA; letter-spacing: 0.5px; text-transform: uppercase;">Cloud Security Posture Management</h2>
      <p style="margin: 4px 0 0 0; font-size: 13px; color: #9CA3AF;">Automated Security Alert Notification</p>
    </div>
    
    <div style="padding: 24px;">
      <div style="display: inline-block; padding: 4px 12px; border-radius: 6px; font-weight: bold; font-size: 12px; letter-spacing: 0.5px; background-color: {severity_color}20; color: {severity_color}; border: 1px solid {severity_color}40; margin-bottom: 16px;">
        {severity} SEVERITY
      </div>

      <h1 style="font-size: 18px; margin: 0 0 16px 0; color: #FFFFFF; font-weight: 700;">{alert_title}</h1>

      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px;">
        <tr>
          <td style="padding: 8px 0; color: #9CA3AF; width: 140px;">Cloud Account:</td>
          <td style="padding: 8px 0; color: #FFFFFF; font-weight: 600;">{account_name}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #9CA3AF;">Account ID:</td>
          <td style="padding: 8px 0; color: #E5E7EB; font-family: monospace;">{account_id}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #9CA3AF;">Risk Score:</td>
          <td style="padding: 8px 0; color: #F87171; font-weight: 600;">{risk_score}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #9CA3AF;">Status:</td>
          <td style="padding: 8px 0; color: #E5E7EB;">{status}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #9CA3AF;">Detected:</td>
          <td style="padding: 8px 0; color: #E5E7EB;">{detected_time}</td>
        </tr>
      </table>

      <div style="background-color: #1F2937; border-left: 4px solid {severity_color}; padding: 14px; border-radius: 4px; margin-bottom: 20px;">
        <h4 style="margin: 0 0 6px 0; font-size: 13px; color: #D1D5DB;">Description</h4>
        <p style="margin: 0; font-size: 13px; color: #E5E7EB; line-height: 1.5;">{description}</p>
      </div>

      <div style="background-color: #0F172A; border: 1px solid #1E293B; padding: 14px; border-radius: 6px; margin-bottom: 24px;">
        <h4 style="margin: 0 0 6px 0; font-size: 13px; color: #38BDF8;">Recommended Action</h4>
        <p style="margin: 0; font-size: 13px; color: #CBD5E1; line-height: 1.5;">{remediation}</p>
      </div>

      <div style="text-align: center; margin: 24px 0 12px 0;">
        <a href="{alert_url}" style="background-color: #2563EB; color: #FFFFFF; text-decoration: none; padding: 12px 28px; border-radius: 8px; font-weight: 600; font-size: 13px; display: inline-block;">
          View in Security Console &rarr;
        </a>
      </div>
    </div>

    <div style="background-color: #0F172A; padding: 16px 24px; border-top: 1px solid #1F2937; font-size: 11px; color: #6B7280; text-align: center;">
      This notification was generated by your CSPM continuous monitoring system.<br>
      Automated read-only security assessment.
    </div>
  </div>
</body>
</html>"""

        return text_body, html_body

    @classmethod
    def send_alert_email(
        cls,
        recipient_email: str,
        alert: SecurityAlert,
        cloud_account: CloudAccount,
    ) -> Tuple[bool, str]:
        """
        Transmits the security alert email via SMTP to the verified owner.
        Returns: (success: bool, status_message: str)
        Safe: Never raises unhandled exceptions. Never logs SMTP passwords.
        """
        if not cls.is_enabled():
            return False, "CSPM email notifications disabled (CSPM_EMAIL_ENABLED=false)"

        if not recipient_email or "@" not in recipient_email:
            return False, f"Invalid recipient email: {recipient_email}"

        smtp_host = getattr(settings, "CSPM_SMTP_HOST", "").strip()
        smtp_port = int(getattr(settings, "CSPM_SMTP_PORT", 587))
        smtp_user = getattr(settings, "CSPM_SMTP_USERNAME", "").strip()
        smtp_pass = getattr(settings, "CSPM_SMTP_PASSWORD", "")
        smtp_from = getattr(settings, "CSPM_SMTP_FROM", "noreply@cspm-security.local").strip()
        use_tls = bool(getattr(settings, "CSPM_SMTP_USE_TLS", True))

        if not smtp_host:
            logger.warning("Email transmission skipped: CSPM_SMTP_HOST not configured.")
            return False, "SMTP host not configured"

        subject = cls.format_subject(alert)
        text_body, html_body = cls.build_email_bodies(alert, cloud_account)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = smtp_from
        msg["To"] = recipient_email

        msg.attach(MIMEText(text_body, "plain", "utf-8"))
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        try:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
                if use_tls:
                    server.starttls()
                if smtp_user and smtp_pass:
                    server.login(smtp_user, smtp_pass)
                server.send_message(msg)

            logger.info(
                f"Security alert email sent successfully to {recipient_email} for alert {alert.id} "
                f"({alert.alert_type}, {alert.severity})"
            )
            return True, "Email sent successfully"

        except Exception as e:
            # Crucial: Log error message without exposing credentials
            logger.error(
                f"Failed to send security alert email to {recipient_email} for alert {alert.id}: {type(e).__name__} - {e}"
            )
            return False, f"SMTP delivery failed: {type(e).__name__}"
